baseURL = "https://mamun05.github.io/"
languageCode = "en-us"
title = "Mamun's Blog"
# theme = "nostyleplease"  # Commented out since we're using the theme files directly

[module]
  [module.hugoVersion]
    extended=true
    min = "0.41.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'rrt'
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[params]
  author = "Mamun"
  description = "Personal blog and portfolio"
  [params.theme_config]
    appearance = "auto"
    back_home_text = ".."
    date_format = "2006-01-02"
    isListGroupByDate = false
